import type { FastifyInstance } from 'fastify'
import { eq, and, sql, gte, lt } from 'drizzle-orm'
import { db, budgets, leads, offlineConversions, funnelStages, adsPlatformIntegrations, crmIntegrations } from '@ads/db'

export async function dashboardRoutes(app: FastifyInstance) {
  app.addHook('preHandler', app.authenticate)

  // GET /api/v1/dashboard/summary?month=4&year=2026&clientId=xxx
  app.get('/summary', async (request, reply) => {
    const query = request.query as { month?: string; year?: string; clientId?: string }
    const now = new Date()
    const month = query.month ? parseInt(query.month) : now.getMonth() + 1
    const year = query.year ? parseInt(query.year) : now.getFullYear()
    const tid = request.user.tid
    const clientId = query.clientId || null

    const budgetWhere = clientId
      ? and(eq(budgets.tenantId, tid), eq(budgets.month, month), eq(budgets.year, year), eq(budgets.clientId, clientId))
      : and(eq(budgets.tenantId, tid), eq(budgets.month, month), eq(budgets.year, year))

    // Filter leads by month/year (entry date)
    const periodStart = new Date(year, month - 1, 1)
    const periodEnd = new Date(year, month, 1) // exclusive upper bound
    const leadsWhere = clientId
      ? and(eq(leads.tenantId, tid), eq(leads.clientId, clientId), gte(leads.createdAt, periodStart), lt(leads.createdAt, periodEnd))
      : and(eq(leads.tenantId, tid), gte(leads.createdAt, periodStart), lt(leads.createdAt, periodEnd))

    const [budgetRows, leadRows, conversionRows, stageRows, platformCount, crmCount] =
      await Promise.all([
        db.query.budgets.findMany({ where: budgetWhere }),
        db.select({
          status: leads.status,
          count: sql<number>`count(*)::int`,
        })
          .from(leads)
          .where(leadsWhere)
          .groupBy(leads.status),
        db.select({
          platform: offlineConversions.platform,
          count: sql<number>`count(*)::int`,
        })
          .from(offlineConversions)
          .where(and(eq(offlineConversions.tenantId, tid), eq(offlineConversions.status, 'active')))
          .groupBy(offlineConversions.platform),
        db.select({
          stageId: leads.stageId,
          stageName: funnelStages.name,
          count: sql<number>`count(*)::int`,
        })
          .from(leads)
          .leftJoin(funnelStages, eq(leads.stageId, funnelStages.id))
          .where(leadsWhere)
          .groupBy(leads.stageId, funnelStages.name),
        db
          .select({ count: sql<number>`count(*)::int` })
          .from(adsPlatformIntegrations)
          .where(and(eq(adsPlatformIntegrations.tenantId, tid), eq(adsPlatformIntegrations.status, 'active'))),
        db
          .select({ count: sql<number>`count(*)::int` })
          .from(crmIntegrations)
          .where(and(eq(crmIntegrations.tenantId, tid), eq(crmIntegrations.status, 'active'))),
      ])

    const totalPlanned = budgetRows.reduce((s, b) => s + parseFloat(b.plannedAmount), 0)
    const totalSpent = budgetRows.reduce((s, b) => s + parseFloat(b.spentAmount), 0)
    const crmLeads = leadRows.reduce((s, r) => s + r.count, 0)
    const qualifiedLeads = leadRows.find((r) => r.status === 'qualified')?.count ?? 0
    const wonLeads = leadRows.find((r) => r.status === 'won')?.count ?? 0
    const totalConversions = conversionRows.reduce((s, r) => s + r.count, 0)

    // Fetch integrations for budget rows — get name + meta (impressions/clicks/CTR)
    const integrationIds = budgetRows.map((b) => b.integrationId).filter(Boolean) as string[]
    const integrationRows = integrationIds.length > 0
      ? await db.query.adsPlatformIntegrations.findMany({
          where: (t, { inArray }) => inArray(t.id, integrationIds),
          columns: { id: true, name: true, meta: true, lastSyncAt: true },
        })
      : []
    const integrationMap = Object.fromEntries(integrationRows.map((i) => [i.id, i]))

    // Helper to get meta from budget row with fallback to integration meta
    const getBudgetMeta = (b: any) => {
      const bm = b.meta as any
      if (bm && Object.keys(bm).length > 0) return bm
      return (b.integrationId ? (integrationMap[b.integrationId]?.meta as any) : null) ?? {}
    }

    // Lead breakdown by source from Meta Ads data
    const totalMetaLeads = budgetRows.reduce((s, b) => s + (getBudgetMeta(b).leads ?? 0), 0)
    const totalLeadAd = budgetRows.reduce((s, b) => s + (getBudgetMeta(b).leadsLeadAd ?? 0), 0)
    const totalSiteLead = budgetRows.reduce((s, b) => s + (getBudgetMeta(b).leadsSite ?? 0), 0)

    // "Total de Leads" = Meta campaign leads (from ad platform sync).
    // CRM-imported contacts (HubSpot/webhook) are in the DB for offline conversion
    // but should NOT inflate this KPI — they weren't generated by campaigns this month.
    const totalLeads = totalMetaLeads > 0 ? totalMetaLeads : crmLeads

    const totalImpressions = budgetRows.reduce((s, b) => s + (getBudgetMeta(b).impressions ?? 0), 0)
    const totalClicks = budgetRows.reduce((s, b) => s + (getBudgetMeta(b).clicks ?? 0), 0)
    const avgCtr = totalImpressions > 0 ? (totalClicks / totalImpressions) * 100 : 0
    const avgCpm = totalSpent > 0 && totalImpressions > 0 ? (totalSpent / totalImpressions) * 1000 : 0
    const cpl = totalLeads > 0 && totalSpent > 0 ? totalSpent / totalLeads : 0

    const budgetByPlatform = budgetRows.map((b) => {
      const planned = parseFloat(b.plannedAmount)
      const spent = parseFloat(b.spentAmount)
      const integration = b.integrationId ? integrationMap[b.integrationId] : null
      // Use budget.meta (per-month) first, fall back to integration.meta (latest sync)
      const meta = (b.meta as any && Object.keys(b.meta as any).length > 0)
        ? (b.meta as any)
        : ((integration?.meta as any) ?? {})
      return {
        id: b.id,
        platform: b.platform,
        integrationId: b.integrationId ?? null,
        integrationName: integration?.name ?? null,
        plannedAmount: planned,
        spentAmount: spent,
        remainingAmount: planned - spent,
        percentUsed: planned > 0 ? Math.round((spent / planned) * 100) : 0,
        currency: b.currency,
        month,
        year,
        impressions: meta.impressions ?? 0,
        clicks: meta.clicks ?? 0,
        ctr: meta.ctr ?? 0,
        cpm: meta.cpm ?? 0,
        leads: meta.leads ?? 0,
        cpl: meta.cpl ?? 0,
        lastSyncAt: meta.lastSyncAt ?? integration?.lastSyncAt ?? null,
      }
    })

    return reply.send({
      data: {
        period: { month, year },
        totalBudgetPlanned: totalPlanned,
        totalBudgetSpent: totalSpent,
        totalLeads,
        crmLeads,
        metaLeads: totalMetaLeads,
        leadsLeadAd: totalLeadAd,
        leadsSite: totalSiteLead,
        leadsOrganic: crmLeads > 0
          ? Math.max(0, crmLeads - totalMetaLeads)
          : 0,
        totalQualifiedLeads: qualifiedLeads,
        totalWon: wonLeads,
        totalConversionsSent: totalConversions,
        totalImpressions,
        totalClicks,
        avgCtr: Math.round(avgCtr * 100) / 100,
        avgCpm: Math.round(avgCpm * 100) / 100,
        cpl: Math.round(cpl * 100) / 100,
        activePlatforms: platformCount[0]?.count ?? 0,
        activeCrms: crmCount[0]?.count ?? 0,
        conversionsByPlatform: conversionRows.map((r) => ({ platform: r.platform, count: r.count })),
        leadsByStage: stageRows.map((r) => ({ stageName: r.stageName ?? 'Sem etapa', count: r.count })),
        budgetByPlatform,
      },
    })
  })
}
